apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fleet-local
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
