apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
  namespace: nginx-testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: nfsroot
