apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-nginx-ingress
  namespace: nginx-testing
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80
